add_library(lol_platform_ports INTERFACE)
target_include_directories(lol_platform_ports INTERFACE include)
lol_register(lol_platform_ports platform ports)
if(NOT LIGHTOVERLEAF_BUILD_ELECTRON)
add_library(lol_platform_lifecycle STATIC kbrowserlifecycle.cpp)
target_link_libraries(lol_platform_lifecycle PUBLIC lol_platform_ports)
lol_register(lol_platform_lifecycle platform lifecycle)
add_library(lol_platform_qt STATIC qt/kqtplatform.cpp)
lol_register(lol_platform_qt platform qt)
add_library(lol_platform_cef STATIC cef/kcefplatform.cpp)
lol_register(lol_platform_cef platform cef)
endif()
add_library(lol_platform_windows STATIC windows/kwindowsplatform.cpp)
lol_register(lol_platform_windows platform windows)
add_library(lol_platform_worker STATIC worker/kworkerexecutor.cpp)
target_link_libraries(lol_platform_worker PUBLIC lol_platform_ports)
lol_register(lol_platform_worker platform worker)

