add_library(lol_workspace_inbound INTERFACE)
target_include_directories(lol_workspace_inbound INTERFACE inbound/include)
target_link_libraries(lol_workspace_inbound INTERFACE lol_kernel)
lol_register(lol_workspace_inbound inbound workspace)
add_library(lol_workspace_outbound INTERFACE)
target_include_directories(lol_workspace_outbound INTERFACE outbound/include)
target_link_libraries(lol_workspace_outbound INTERFACE lol_kernel)
lol_register(lol_workspace_outbound outbound workspace)
add_library(lol_workspace_app STATIC src/kworkspaces.cpp)
target_link_libraries(lol_workspace_app PRIVATE lol_workspace_domain lol_workspace_inbound lol_workspace_outbound)
lol_register(lol_workspace_app app workspace)
