#include <lightoverleaf/export/inbound/ikexports.h>
#include <lightoverleaf/export/adapters/klocalexportstore.h>
#include <windows.h>
#include <filesystem>
#include <fstream>
#include <iostream>
using namespace lightoverleaf;using namespace lightoverleaf::exporting;namespace fs=std::filesystem;
namespace { std::string utf8(const fs::path& value){const auto encoded=value.u8string();return {reinterpret_cast<const char*>(encoded.data()),encoded.size()};} }
int main(){int failures=0;auto check=[&](bool value,const char* label){if(!value){++failures;std::cerr<<label<<'\n';}};std::error_code error;const fs::path base=fs::temp_directory_path()/(L"LightOverLeaf-export-"+std::to_wstring(GetCurrentProcessId()));fs::remove_all(base,error);fs::create_directories(base,error);auto exports=createExports(createLocalExportStore());
 const fs::path target=base/L"论文导出";fs::create_directory(target,error);auto authorization=exports->authorize("session-a",utf8(target),1000);check(std::holds_alternative<KExportDestination>(authorization),"empty target authorized");if(auto* destination=std::get_if<KExportDestination>(&authorization)){check(destination->m_token.find(utf8(target))==std::string::npos,"token does not expose destination path");KExportCommand command{"session-a",destination->m_token,7,{{"main.tex","main"},{"sections/intro.tex","intro"}}};auto result=exports->exportProject(command,1100);check(std::holds_alternative<KExportResult>(result)&&std::get<KExportResult>(result).m_complete&&std::get<KExportResult>(result).m_writtenFiles.size()==2&&fs::exists(target/L"main.tex")&&fs::exists(target/L"sections"/L"intro.tex"),"atomic directory export");check(std::holds_alternative<KError>(exports->exportProject(command,1200)),"destination token is single use");}
 const fs::path cross=base/L"cross";fs::create_directory(cross,error);auto crossAuthorization=exports->authorize("session-a",utf8(cross),2000);if(auto* destination=std::get_if<KExportDestination>(&crossAuthorization)){KExportCommand command{"session-b",destination->m_token,8,{{"main.tex","x"}}};check(std::holds_alternative<KError>(exports->exportProject(command,2100))&&fs::is_empty(cross),"token cannot cross sessions");}
 const fs::path expired=base/L"expired";fs::create_directory(expired,error);auto expiredAuthorization=exports->authorize("session-a",utf8(expired),3000);if(auto* destination=std::get_if<KExportDestination>(&expiredAuthorization)){KExportCommand command{"session-a",destination->m_token,9,{{"main.tex","x"}}};check(std::holds_alternative<KError>(exports->exportProject(command,603001))&&fs::is_empty(expired),"expired token rejected");}
 const fs::path nonempty=base/L"nonempty";fs::create_directory(nonempty,error);std::ofstream(nonempty/L"keep.txt")<<"keep";check(std::holds_alternative<KError>(exports->authorize("session-a",utf8(nonempty),4000)),"nonempty destination rejected");KExportCommand invalid{"session-a",std::string(64,'a'),10,{{"../outside.tex","x"}}};check(std::holds_alternative<KError>(exports->exportProject(invalid,4100)),"path traversal rejected in application");
 const fs::path cancelled=base/L"cancelled";fs::create_directory(cancelled,error);auto cancelledAuthorization=exports->authorize("session-a",utf8(cancelled),5000);if(auto* destination=std::get_if<KExportDestination>(&cancelledAuthorization)){std::stop_source stop;stop.request_stop();KExportCommand command{"session-a",destination->m_token,11,{{"main.tex","x"}}};auto result=exports->exportProject(command,5100,stop.get_token());check(std::holds_alternative<KError>(result)&&std::get<KError>(result).m_code==KErrorCode::Cancelled&&fs::is_empty(cancelled),"cancelled export leaves target unchanged");}
 fs::remove_all(base,error);return failures?1:0;}
