#include <lightoverleaf/preferences/adapters/ksqlitepreferencesstore.h>
#include <sqlite3.h>
#include <mutex>
namespace lightoverleaf::preferences {
class KSqlitePreferencesStore final:public IKPreferencesStore{public:explicit KSqlitePreferencesStore(sqlite3*d):m_db(d){}~KSqlitePreferencesStore()override{sqlite3_close(m_db);}
 KResult<KStoredPreferences>load()const override{std::scoped_lock lock(m_mutex);sqlite3_stmt*s=nullptr;const char*q="SELECT tex_root,engine,timeout_ms,auto_compile FROM preferences WHERE id=1";if(sqlite3_prepare_v2(m_db,q,-1,&s,nullptr)!=SQLITE_OK)return error();struct Final{sqlite3_stmt*s;~Final(){sqlite3_finalize(s);}}f{s};if(sqlite3_step(s)==SQLITE_ROW)return KStoredPreferences{reinterpret_cast<const char*>(sqlite3_column_text(s,0)),reinterpret_cast<const char*>(sqlite3_column_text(s,1)),static_cast<unsigned>(sqlite3_column_int(s,2)),sqlite3_column_int(s,3)!=0};return KStoredPreferences{"","xelatex",120000,false};}
 KResult<bool>save(const KStoredPreferences&v)override{std::scoped_lock lock(m_mutex);sqlite3_stmt*s=nullptr;const char*q="INSERT INTO preferences(id,tex_root,engine,timeout_ms,auto_compile) VALUES(1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET tex_root=excluded.tex_root,engine=excluded.engine,timeout_ms=excluded.timeout_ms,auto_compile=excluded.auto_compile";if(sqlite3_prepare_v2(m_db,q,-1,&s,nullptr)!=SQLITE_OK)return error();struct Final{sqlite3_stmt*s;~Final(){sqlite3_finalize(s);}}f{s};sqlite3_bind_text(s,1,v.m_texRoot.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,v.m_engine.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,3,static_cast<int>(v.m_timeoutMs));sqlite3_bind_int(s,4,v.m_autoCompile?1:0);return sqlite3_step(s)==SQLITE_DONE?KResult<bool>{true}:KResult<bool>{error()};}
 private:KError error()const{return {KErrorCode::Unavailable,"preferences.storageFailure",true};}sqlite3*m_db;mutable std::mutex m_mutex;};
KResult<std::shared_ptr<IKPreferencesStore>>createSqlitePreferencesStore(const std::string&path){sqlite3*d=nullptr;if(sqlite3_open_v2(path.c_str(),&d,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,nullptr)!=SQLITE_OK){if(d)sqlite3_close(d);return KError{KErrorCode::Unavailable,"preferences.storageFailure",true};}const char*ddl="CREATE TABLE IF NOT EXISTS preferences(id INTEGER PRIMARY KEY CHECK(id=1),tex_root TEXT NOT NULL,engine TEXT NOT NULL,timeout_ms INTEGER NOT NULL,auto_compile INTEGER NOT NULL)";if(sqlite3_exec(d,ddl,nullptr,nullptr,nullptr)!=SQLITE_OK){sqlite3_close(d);return KError{KErrorCode::Unavailable,"preferences.storageFailure",true};}return std::shared_ptr<IKPreferencesStore>(std::make_shared<KSqlitePreferencesStore>(d));}
}
