add_library(lol_document_inbound INTERFACE)
target_include_directories(lol_document_inbound INTERFACE inbound/include)
target_link_libraries(lol_document_inbound INTERFACE lol_kernel)
lol_register(lol_document_inbound inbound document)
add_library(lol_document_outbound INTERFACE)
target_include_directories(lol_document_outbound INTERFACE outbound/include)
target_link_libraries(lol_document_outbound INTERFACE lol_kernel)
lol_register(lol_document_outbound outbound document)
add_library(lol_document_app STATIC src/kdocuments.cpp)
target_link_libraries(lol_document_app PRIVATE lol_document_domain lol_document_inbound lol_document_outbound)
lol_register(lol_document_app app document)
