# Metadata is exported from real CMake targets and their actual link properties.
function(lol_register target layer module)
  set_target_properties(${target} PROPERTIES LOL_LAYER "${layer}" LOL_MODULE "${module}")
  set_property(GLOBAL APPEND PROPERTY LOL_TARGETS ${target})
endfunction()

function(lol_check_registration directory)
  get_property(localTargets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(target IN LISTS localTargets)
    get_target_property(kind ${target} TYPE)
    if(kind STREQUAL "UTILITY")
      continue()
    endif()
    get_target_property(layer ${target} LOL_LAYER)
    if(NOT layer)
      message(FATAL_ERROR "Target missing architecture metadata: ${target}")
    endif()
    foreach(property INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES)
      get_target_property(paths ${target} ${property})
      foreach(path IN LISTS paths)
        if(path STREQUAL "${PROJECT_SOURCE_DIR}" OR path STREQUAL "${LOL_REPO_ROOT}/backend"
          OR path STREQUAL "${LOL_REPO_ROOT}"
          OR path MATCHES "/backend/latexlocalservice/(app|texengine|workspace|persistence|transport)$")
          message(FATAL_ERROR "Broad include root forbidden: ${target} -> ${path}")
        endif()
      endforeach()
    endforeach()
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    cmake_path(IS_PREFIX PROJECT_SOURCE_DIR "${child}" NORMALIZE isOwnDirectory)
    if(isOwnDirectory)
      lol_check_registration("${child}")
    endif()
  endforeach()
endfunction()

function(lol_export_architecture)
  lol_check_registration("${CMAKE_CURRENT_SOURCE_DIR}")
  get_property(targets GLOBAL PROPERTY LOL_TARGETS)
  set(records "")
  foreach(target IN LISTS targets)
    get_target_property(layer ${target} LOL_LAYER)
    get_target_property(module ${target} LOL_MODULE)
    get_target_property(kind ${target} TYPE)
    get_target_property(links ${target} LINK_LIBRARIES)
    get_target_property(interfaceLinks ${target} INTERFACE_LINK_LIBRARIES)
    set(edges "")
    foreach(link IN LISTS links interfaceLinks)
      if(link AND NOT link MATCHES "-NOTFOUND$" AND NOT link MATCHES "^::@")
        string(REGEX REPLACE "^\\$<LINK_ONLY:([^>]+)>$" "\\1" link "${link}")
        list(APPEND edges "\" ${link}\"")
      endif()
    endforeach()
    list(REMOVE_DUPLICATES edges)
    string(JOIN "," edgeJson ${edges})
    list(APPEND records "{\"name\":\"${target}\",\"layer\":\"${layer}\",\"module\":\"${module}\",\"kind\":\"${kind}\",\"links\":[${edgeJson}]}")
  endforeach()
  string(JOIN ",\n" json ${records})
  file(WRITE "${CMAKE_BINARY_DIR}/architecture.json" "[${json}]")
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/tools/architecture/check.py"
    --graph "${CMAKE_BINARY_DIR}/architecture.json" --source "${LOL_REPO_ROOT}"
    COMMAND_ERROR_IS_FATAL ANY)
endfunction()

