add_library(lol_preview_inbound INTERFACE)
target_include_directories(lol_preview_inbound INTERFACE inbound/include)
target_link_libraries(lol_preview_inbound INTERFACE lol_kernel)
lol_register(lol_preview_inbound inbound preview)
add_library(lol_preview_outbound INTERFACE)
target_include_directories(lol_preview_outbound INTERFACE outbound/include)
target_link_libraries(lol_preview_outbound INTERFACE lol_kernel)
lol_register(lol_preview_outbound outbound preview)
add_library(lol_preview_app STATIC src/kpreviewartifacts.cpp)
target_link_libraries(lol_preview_app PRIVATE lol_preview_domain lol_preview_inbound lol_preview_outbound)
lol_register(lol_preview_app app preview)
