add_library(lol_navigation_inbound INTERFACE)
target_include_directories(lol_navigation_inbound INTERFACE inbound/include)
target_link_libraries(lol_navigation_inbound INTERFACE lol_kernel)
lol_register(lol_navigation_inbound inbound navigation)
add_library(lol_navigation_outbound INTERFACE)
target_include_directories(lol_navigation_outbound INTERFACE outbound/include)
target_link_libraries(lol_navigation_outbound INTERFACE lol_kernel)
lol_register(lol_navigation_outbound outbound navigation)
add_library(lol_navigation_app STATIC src/knavigation.cpp)
target_link_libraries(lol_navigation_app PRIVATE lol_navigation_domain lol_navigation_inbound lol_navigation_outbound)
lol_register(lol_navigation_app app navigation)
