if(NOT WIN32 OR NOT MSVC OR NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "Desktop requires Windows x64 and MSVC. Disable LIGHTOVERLEAF_BUILD_DESKTOP for core tests.")
endif()
if(NOT IS_DIRECTORY "${LIGHTOVERLEAF_THIRDPARTY_ROOT}")
  message(FATAL_ERROR "Native dependency root missing. Set LIGHTOVERLEAF_THIRDPARTY_ROOT to your Qt/CEF installation.")
endif()
set(CEF_ROOT "${LIGHTOVERLEAF_THIRDPARTY_ROOT}/cef_binary_150.0.14+g7c1aa68+chromium-150.0.7871.129_windows64" CACHE PATH "CEF binary distribution")
if(NOT EXISTS "${CEF_ROOT}/cmake/FindCEF.cmake")
  message(FATAL_ERROR "CEF not found at CEF_ROOT. Set CEF_ROOT or LIGHTOVERLEAF_THIRDPARTY_ROOT.")
endif()
list(PREPEND CMAKE_PREFIX_PATH "${LIGHTOVERLEAF_THIRDPARTY_ROOT}/vcpkg/installed/x64-windows/share/cmake")
find_package(Qt5 5.15 REQUIRED COMPONENTS Core Gui Widgets)
list(APPEND CMAKE_MODULE_PATH "${CEF_ROOT}/cmake")
set(CEF_RUNTIME_LIBRARY_FLAG "/MD" CACHE STRING "" FORCE)
set(USE_SANDBOX ON CACHE BOOL "" FORCE)
find_package(CEF REQUIRED)
if(MSVC_VERSION LESS 1930)
  message(WARNING "CEF 150 recommends VS2022; validating the installed VS2019 with the Windows SDK compatibility definition.")
  add_compile_definitions(NTDDI_WIN10_FE=0x0A00000A)
endif()
add_subdirectory("${CEF_LIBCEF_DLL_WRAPPER_PATH}" "${CMAKE_BINARY_DIR}/thirdparty/cef-wrapper")
ADD_LOGICAL_TARGET(libcef_lib "${CEF_LIB_DEBUG}" "${CEF_LIB_RELEASE}")
target_sources(lol_platform_qt PRIVATE "${PROJECT_SOURCE_DIR}/backend/latexlocalservice/app/platform/qt/kqtruntime.cpp")
target_include_directories(lol_platform_qt PUBLIC "${PROJECT_SOURCE_DIR}/backend/latexlocalservice/app/platform/qt/include")
target_link_libraries(lol_platform_qt PRIVATE Qt5::Core Qt5::Gui Qt5::Widgets lol_platform_lifecycle PUBLIC lol_platform_ports)
target_sources(lol_platform_cef PRIVATE "${PROJECT_SOURCE_DIR}/backend/latexlocalservice/app/platform/cef/kcefruntime.cpp")
target_include_directories(lol_platform_cef PUBLIC "${PROJECT_SOURCE_DIR}/backend/latexlocalservice/app/platform/cef/include")
target_include_directories(lol_platform_cef SYSTEM PRIVATE "${CEF_ROOT}")
target_compile_definitions(lol_platform_cef PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN NTDDI_WIN10_FE=0x0A00000A)
target_link_libraries(lol_platform_cef PRIVATE libcef_lib libcef_dll_wrapper bcrypt PUBLIC lol_platform_ports)
target_compile_definitions(lol_transport_cef PRIVATE LOL_WITH_CEF NOMINMAX WIN32_LEAN_AND_MEAN NTDDI_WIN10_FE=0x0A00000A)
target_include_directories(lol_transport_cef SYSTEM PRIVATE "${CEF_ROOT}")
target_link_libraries(lol_transport_cef PRIVATE libcef_lib libcef_dll_wrapper)

