add_library(lol_preferences_inbound INTERFACE)
target_include_directories(lol_preferences_inbound INTERFACE inbound/include)
target_link_libraries(lol_preferences_inbound INTERFACE lol_kernel)
lol_register(lol_preferences_inbound inbound preferences)
add_library(lol_preferences_outbound INTERFACE)
target_include_directories(lol_preferences_outbound INTERFACE outbound/include)
target_link_libraries(lol_preferences_outbound INTERFACE lol_kernel)
lol_register(lol_preferences_outbound outbound preferences)
add_library(lol_preferences_app STATIC src/kpreferences.cpp)
target_link_libraries(lol_preferences_app PRIVATE lol_preferences_domain lol_preferences_inbound lol_preferences_outbound)
lol_register(lol_preferences_app app preferences)
